# Generated by Django 4.0.4 on 2023-01-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_user_delete_usercustom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
