# Generated by Django 4.0.4 on 2023-01-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_paitent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
