# Generated by Django 4.0.4 on 2023-01-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='bloogroup',
            field=models.CharField(blank=True, default=None, max_length=14),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
