# Generated by Django 4.0.4 on 2023-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_user_address_user_bloogroup_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloogroup',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
