# Generated by Django 4.0.4 on 2023-01-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_alter_user_address_alter_user_bloogroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
