# Generated by Django 4.0.4 on 2023-01-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_remove_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bloogroup',
        ),
    ]
