# Generated by Django 4.0.4 on 2023-01-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0011_remove_user_bloogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bloogroup',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
