# Generated by Django 4.0.4 on 2023-01-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_alter_user_email_alter_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bloogroup',
            new_name='bloodgroup',
        ),
    ]
