# Generated by Django 4.0.4 on 2023-01-06 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0016_rename_bloogroup_user_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, max_length=8, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=14, null=True)),
                ('prescription', models.TextField()),
                ('Doctorname', models.CharField(max_length=40)),
                ('Record_id', models.UUIDField(default=uuid.uuid4)),
                ('patientname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
